apiVersion: v1
kind: Service
metadata:
  name: {{ include "redmine.fullname" . }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: redmine.devsecops.or.kr.
  labels:
{{ include "redmine.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "redmine.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
